language: python

jobs:
  include:
    - os: linux
      dist: xenial
      python: 3.7
    - os: linux
      dist: xenial
      python: 3.8
      env: COVERAGE_SCAN=1
      after_success:
        - codecov

install:
  - pip3 install --upgrade pip
  - pip install .[testing]
  - |
    if [[ "$COVERAGE_SCAN" == 1 ]]; then
      pip install pytest-cov codecov
    fi

script:
  - |
    if [[ "$COVERAGE_SCAN" == 1 ]]; then
      pytest -v --cov=liso/ liso
    else
      pytest -v liso
    fi
